Select: add support for typeahead select
RedHatQE/widgetastic.patternfly5 pull request #51
Opened 2024-02-19 14:36 UTC by jrusz

When there is an item selected it would click on the clear button instead of the toggle button when trying to access items or calling open(), this fixes that.

2024-02-19 15:41 UTC, jrusz commented
@digitronik Hi, can you review please? 

Also there were some seemingly random failures during the test runs, I had to force push a few times before it all passed, they were tests for other widgets, unrelated to my change though, should we be concerned about that?

2024-02-19 20:22 UTC, jrusz commented
I've actually found some issues with this. Need to update it.

2024-02-20 06:11 UTC, jrusz commented
This should work now, also I've found out that I need it for the `fill` method, it doesn't work without this. I think it's the "Typeahead" select which causes these issues for me with a default value preselected (but the same would happen if you were to select something twice) ... I'll add some tests for this as it seems that select type is not covered.

2024-02-20 08:50 UTC, jrusz commented
I ended up adding a new class for the select as the `read` method didn't work, the selected value is a in separate `input` element instead underneath the button, the rest seems to be fine.

2024-02-20 16:29 UTC, digitronik requested changes
Nice PR :+1: 

Some suggestions
As we are introducing new widget better to maintain it in README as well. 

Special thanks for covering unit tests.  I will take a look on more time after changes.

2024-02-20 16:29 UTC, digitronik commented on src/widgetastic_patternfly5/components/menus/select.py
> +        return self.browser.get_attribute("value", self.text)
Lets make this part of widget directly only single method.
Better to use `input` as name of child widget. 
```
input = TextInput(locator=".//input")
```

2024-02-20 16:29 UTC, digitronik commented on src/widgetastic_patternfly5/components/menus/select.py
> +    BUTTON_LOCATOR = (
Better to overwrite in widget itself. Those limitation can break usage.  Not tested against console dot so.

2024-02-20 17:07 UTC, jrusz commented
@digitronik Is this what you meant?

2024-02-21 14:04 UTC, jrusz commented
I'm not sure why, but the `ouia` component doesn't work if I don't use the Base component type, is it ok like this?

2024-02-21 16:23 UTC, digitronik approved these changes

2024-02-21 16:24 UTC, digitronik commented
@jrusz I'm good with it can you please check jobs

2024-02-21 16:39 UTC, jrusz commented
> @jrusz I'm good with it can you please check jobs

Thank you. I don't know why the jobs fail, like I said in a comment above they fail seemingly randomly. I don't have permissions to restart them, I'd have to force push, can you try restarting them please?

2024-02-26 11:41 UTC, mshriver commented on src/widgetastic_patternfly5/components/menus/select.py
> +        "and not(contains(@class, '-c-select__toggle-clear'))]"
Consider creating a separate locator for the clear button, and a function to click it.

2024-02-26 11:44 UTC, mshriver approved these changes

2024-02-26 11:54 UTC, merged